### ISSUE TITLE
[S2-PBI11] Dashboard User

### ISSUE THREAD

**Issue by Hanifka** [SI-RPL-2022/SI4303_D_WASTEPOINT#10]
Sebagai User ingin melihat aktivitas, data dan status penukaran yang telah dilakukan secara dinamis agar mempermudah saya dalam memperoleh informasi.

**Comment by darielazaka** [comment]
https://user-images.githubusercontent.com/101590031/170911144-a1a6e343-bdc3-4535-8f00-1e680f1e88b6.mp4
