### ISSUE TITLE
[S2-PBI12] Dashboard Admin

### ISSUE THREAD

**Issue by Hanifka** [SI-RPL-2022/SI4303_D_WASTEPOINT#11]
Saya Sebagai admin ingin melihat Dashboard Admin yang berisi data aktivitas pada aplikasi web.

**Comment by RamaRafitraZalino** [comment]
Uploading DashboardAdminFeature.mp4…

**Comment by RamaRafitraZalino** [comment]
Uploading DashboardAdminFeature.mp4…

**Comment by RamaRafitraZalino** [comment]
https://user-images.githubusercontent.com/92160983/170892697-c3305011-d09a-4799-b94f-6cf79c8b534f.mp4
