### ISSUE TITLE
[S2-PBI13] Melakukan Konversi Poin

### ISSUE THREAD

**Issue by Hanifka** [SI-RPL-2022/SI4303_D_WASTEPOINT#12]
Saya sebagai user ingin melakukan penukaran poin dengan uang dengan mudah

**Comment by ekkynovrizalam** [comment]
ditambahkan halaman konfirmasi proses pencarian sudah selesai (seolah olah sudah di transfer). Pada halaman tsb, terdapat nilai nominal yang dicairkan dan sisa poin pengguna.

**Comment by rafifaqilakhanaspie** [comment]
https://user-images.githubusercontent.com/92160979/170863800-bdf0b558-f96c-4e57-9432-19027fe7982a.mp4
