### ISSUE TITLE
[S3-PBI15] Menampilkan Halaman Blog / Artikel

### ISSUE THREAD

**Issue by Hanifka** [SI-RPL-2022/SI4303_D_WASTEPOINT#15]
Sebagai user, saya ingin membaca blog bermanfaat seputar pengelolaan sampah dan informasi lainnya untuk menambah pengetahuan atau menjadi sumber literatur saya.

**Comment by rafifaqilakhanaspie** [comment]
Assalamua'alaikum pak, berikut video penjelasan PBI 16, atas bimbingan dan arahannya saya ucapkan terimakasih.

https://user-images.githubusercontent.com/92160979/174856488-0ced20f2-6ae4-41c5-8ea3-2d9f923a0b67.mp4

**Comment by rafifaqilakhanaspie** [comment]
Assalamua'alaikum pak, berikut video penjelasan PBI 16, atas bimbingan dan arahannya saya ucapkan terimakasih

https://user-images.githubusercontent.com/92160979/174856672-e8d2b9cd-7cf1-4a03-83f5-6527185ed9b8.mp4

.
