### ISSUE TITLE
[S3-PBI17] Halaman Home Dinamis

### ISSUE THREAD

**Issue by muhammadramadhann** [SI-RPL-2022/SI4303_D_WASTEPOINT#17]
Saya sebagai user ingin melihat pencapaian waste point secara real time dan melihat blog tersedia di halaman home sebagai bahan pertimbangan apakah waste point merupakan aplikasi yang tepat untuk saya beraktivitas didalamnya.

**Comment by rafifaqilakhanaspie** [comment]
Usecase Description
![image](https://user-images.githubusercontent.com/92160979/160525964-c5169a2d-49d6-4b04-8f96-c508240436de.png)

Activity Diagram
![PBI16 Optimisasi Home](https://user-images.githubusercontent.com/92160979/160525894-ebfe25e9-0c72-4653-bee2-77deddd6dd8e.png)

Mock Up
![image](https://user-images.githubusercontent.com/92160979/160526015-fcc6a68d-620d-40b7-ad8e-b70d03ddc947.png)
