### ISSUE TITLE
[S1-PBI6] Halaman Produk Pemilahan

### ISSUE THREAD

**Issue by muhammadramadhann** [SI-RPL-2022/SI4303_D_WASTEPOINT#18]
Saya sebagai user ingin melihat produk pemilahan yang tersedia agar saya dapat melakukan penukaran dengan poin yang saya miliki

**Comment by rafifaqilakhanaspie** [comment]
Usecase Description
![image](https://user-images.githubusercontent.com/92160979/160527938-b58206d2-77c9-4414-b5b2-d6a7c56cb77c.png)

Activity Diagram
![PBI6](https://user-images.githubusercontent.com/92160979/160527945-2de069dd-65f1-4e76-a17d-8f08efac88af.png)

Mock Up
![image](https://user-images.githubusercontent.com/92160979/160527961-497a2d17-97de-43f9-8178-3308d902f4dc.png)

**Comment by rafifaqilakhanaspie** [comment]
Selamat pagi pak, ini merupakan PBI tambahan di sprint 1 kelompok kami, terimakasih pak.
