### ISSUE TITLE
[S2-PBI7] Penukaran Poin Dengan Produk

### ISSUE THREAD

**Issue by Hanifka** [SI-RPL-2022/SI4303_D_WASTEPOINT#6]
Saya sebagai user ingin menukarkan poin dengan produk pemilahan sampah agar effort yang saya berikan ketika menukar sampah dapat terbayarkan dan termotivasi untuk memilah sampah dengan baik.

**Comment by ekkynovrizalam** [comment]
ditambahkan proses cek apakah poin cukup atau tidak, ketika tidak cukup di redirect kembali dan diberikan notif poin tidak cukup

**Comment by muhammadramadhann** [comment]
https://user-images.githubusercontent.com/83332442/170867864-96c2b4f2-3fa8-4958-a156-1dde88bc451e.mp4
