### ISSUE TITLE
[S2-PBI9] Detail Status Penukaran Produk

### ISSUE THREAD

**Issue by Hanifka** [SI-RPL-2022/SI4303_D_WASTEPOINT#8]
Saya sebagai user ingin dapat melihat status penukaran produk agar dapat memastikan produk yang ditukarkan sudah diproses atau belum.

**Comment by ekkynovrizalam** [comment]
disatukan di pbi #7

**Comment by Hanifka** [comment]
berikut saya lampirkan Video PBI9(Merged pbi 8)
https://user-images.githubusercontent.com/81150342/170885783-db00c4b6-6588-4b72-a004-acbe5b27b86d.mp4
