### ISSUE TITLE
[S2-PBI10] Fitur Pencarian pada Pengelolaan Data Halaman Admin

### ISSUE THREAD

**Issue by Hanifka** [SI-RPL-2022/SI4303_D_WASTEPOINT#9]
Saya Sebagai admin ingin melihat data yang ada lebih spesifik agar mempermudah dalam pengelolaan data pada halaman admin.

**Comment by fresafebrir01** [comment]
https://user-images.githubusercontent.com/76649539/170863638-8eeb1760-0de3-47c4-9322-be7c94aeb32c.mp4
